# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: sast-scan
      # You may pin to the exact commit or the version.
      # uses: AppThreat/sast-scan-action@4d0f956e6ba3c940a22679fd8fe7cb2e755f3d96
      uses: AppThreat/sast-scan-action@1.0.2
      with:
        # Source directory to scan. Defaults to workspace
        src: /github/workspace
        # Output directory for the generated reports. Defaults to reports
        output: /github/workspace/reports
        # Project type. Eg: java, python, nodejs. Comma separated values allowed.
        type: java
    - name: Build with Maven
      working-directory: /github-actions-java-maven
      run: mvn -B package --file pom.xml -DskipTests=true
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact.jar
        path: /github-actions-java-maven/target/github-actions-java-maven.jar
